### ISSUE TITLE
Trace Access Denied - error 122

### ISSUE THREAD

**Issue by sidprice** [compuphase/Black-Magic-Probe-Book#19] opened 2020-02-17 23:46 UTC
I cannot get BMTrace to work (Windows), I see the above error message.

**Comment by compuphase** [comment] 2020-02-18 10:03
According to winerror.h, code 122 is ERROR_INSUFFICIENT_BUFFER (a data buffer passed to a system call is too small). This might be caused by structure padding.
Has BMTrace worked before, or has it never worked? If it did work before, any idea what changed?

**Comment by sidprice** [comment] 2020-02-18 15:06
Yes, BMTrace has previously worked, I don't remember any changes, perhaps my target is sending larger amounts of data, perhaps 64 bytes each USB packet

**Comment by compuphase** [comment] 2020-02-20 22:06
In commit b37136ed5d3626d4fee467d4a519f895a5f02797 I added an extra code to the error message, to hopefully pinpoint the problem.

**Comment by sidprice** [comment] 2020-02-21 00:30
Unfortunately the mingw build fails, the file "usb-support.h" appears to be missing.

**Comment by compuphase** [comment] 2020-02-21 09:57
Oops, I forgot to add the files to the project before commit. Fixed in commit bbc60b4c72ac6e36c70f329779beec441c4abfd1.

**Comment by sidprice** [comment] 2020-02-21 15:34
![bmtrace_1](https://user-images.githubusercontent.com/12300040/75047949-f1f4f400-5484-11ea-9f97-f51f50901f60.PNG)

Error when running BMTrace.

**Comment by compuphase** [comment] 2020-02-21 19:57
Hmmm... so now the "access denied" error is magically gone and another error pops up. It feels to me like a memory corruption bug.
You can comment out this particular assertion; it does no harm. However, the situation simply should not occur because it implies that time jumps backward...

**Comment by sidprice** [comment] 2020-02-22 20:36
I commented out the assertion and BMTrace now works

**Comment by compuphase** [comment] 2020-07-21 09:13
Commit ffc80c9d9ca124d696b43da388e0fed89f2aeab6 has a fix for the bug signalled by the assertion. When multiple trace messages arrive in a single USB packet, the timestamp on the 2nd (and further) was set incorrectly.

**Closed as completed by compuphase** 2020-07-21 09:13 UTC
Labels: bug
